import fs from 'fs'
import path from 'path'

import { WINDOWS_PORTABLE_EXECUTABLE_NAME } from '../../shared/update.types'
import { getUpdateCachePaths } from './update-paths'

type CreateUpdateApplyScriptParams = {
  latestVersion: string
  appPid: number
  installDir: string
  extractedAppRoot: string
  targetExePath: string
}

type UpdateApplyScriptInfo = {
  scriptPath: string
  logPath: string
}

function escapeBatchValue(value: string): string {
  return value.replace(/%/g, '%%')
}

export async function createUpdateApplyScript({
  latestVersion,
  appPid,
  installDir,
  extractedAppRoot,
  targetExePath
}: CreateUpdateApplyScriptParams): Promise<UpdateApplyScriptInfo> {
  const cachePaths = getUpdateCachePaths(latestVersion, `apply-${latestVersion}`)
  const scriptPath = path.join(cachePaths.versionDir, `apply-update-${latestVersion}.cmd`)
  const logPath = path.join(cachePaths.versionDir, `apply-update-${latestVersion}.log`)
  const sourceExePath = path.join(extractedAppRoot, WINDOWS_PORTABLE_EXECUTABLE_NAME)
  const sourceAppAsarPath = path.join(extractedAppRoot, 'resources', 'app.asar')
  const targetAppAsarPath = path.join(installDir, 'resources', 'app.asar')
  const isDevWinUnpackedInstallDir = installDir
    .toLowerCase()
    .includes(`${path.sep}dist${path.sep}win-unpacked`)

  await fs.promises.mkdir(cachePaths.versionDir, { recursive: true })

  const script = [
    '@echo off',
    'setlocal enableextensions enabledelayedexpansion',
    `set "APP_PID=${appPid}"`,
    `set "INSTALL_DIR=${escapeBatchValue(installDir)}"`,
    `set "SOURCE_DIR=${escapeBatchValue(extractedAppRoot)}"`,
    `set "SOURCE_EXE=${escapeBatchValue(sourceExePath)}"`,
    `set "SOURCE_APP_ASAR=${escapeBatchValue(sourceAppAsarPath)}"`,
    `set "TARGET_EXE=${escapeBatchValue(targetExePath)}"`,
    `set "TARGET_APP_ASAR=${escapeBatchValue(targetAppAsarPath)}"`,
    `set "LOG_PATH=${escapeBatchValue(logPath)}"`,
    `set "ENUM_OUTPUT=${escapeBatchValue(`${logPath}.entries.tmp`)}"`,
    'set "WAIT_TIMEOUT_SECONDS=20"',
    'set "WAIT_ELAPSED=0"',
    'call :log "script started"',
    'call :log "installDir=%INSTALL_DIR%"',
    'call :log "sourceDir=%SOURCE_DIR%"',
    'call :log "sourceExe=%SOURCE_EXE%"',
    'call :log "sourceAppAsar=%SOURCE_APP_ASAR%"',
    'call :log "targetExe=%TARGET_EXE%"',
    'call :log "targetAppAsar=%TARGET_APP_ASAR%"',
    'call :log "logPath=%LOG_PATH%"',
    `if "${isDevWinUnpackedInstallDir ? '1' : '0'}"=="1" call :log "install dir points to dist\\win-unpacked; dev/build tooling may keep files locked"`,
    'call :log "waiting for app process %APP_PID% to exit"',
    'call :log "wait target pid=%APP_PID%"',
    ':wait_for_app_exit',
    'call :log "checking pid %APP_PID% (elapsed !WAIT_ELAPSED!s)"',
    'call :check_pid_running',
    'if errorlevel 1 (',
    '  call :log "pid exited"',
    '  goto wait_for_app_exit_done',
    ')',
    'call :log "pid still alive"',
    'if !WAIT_ELAPSED! GEQ %WAIT_TIMEOUT_SECONDS% (',
    '  call :log "wait for app process timed out"',
    '  call :log "taskkill start for pid %APP_PID%"',
    '  taskkill /PID %APP_PID% /T /F >> "%LOG_PATH%" 2>&1',
    '  if errorlevel 1 (',
    '    call :log "taskkill failed for pid %APP_PID%"',
    '  ) else (',
    '    call :log "taskkill succeeded for pid %APP_PID%"',
    '  )',
    '  timeout /t 2 /nobreak >nul',
    '  call :log "checking pid %APP_PID% after taskkill"',
    '  call :check_pid_running',
    '  if errorlevel 1 (',
    '    call :log "pid exited after taskkill"',
    '    goto wait_for_app_exit_done',
    '  )',
    '  call :log "pid still alive after taskkill, aborting"',
    '  exit /b 21',
    ')',
    'set /a WAIT_ELAPSED+=1',
    'timeout /t 1 /nobreak >nul',
    'goto wait_for_app_exit',
    ':wait_for_app_exit_done',
    'call :log "app process exit confirmed"',
    'call :log "extra lock settle wait start"',
    'timeout /t 1 /nobreak >nul',
    'call :log "extra lock settle wait finished"',
    'if not exist "%SOURCE_DIR%" (',
    '  call :log "source directory missing"',
    '  exit /b 10',
    ')',
    'if not exist "%SOURCE_EXE%" (',
    '  call :log "source exe missing, aborting"',
    '  exit /b 14',
    ')',
    'call :log "source exe found"',
    'if not exist "%SOURCE_APP_ASAR%" (',
    '  call :log "source app.asar missing, aborting"',
    '  exit /b 16',
    ')',
    'call :log "source app.asar found"',
    'if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"',
    'if not exist "%TARGET_EXE%" (',
    '  call :log "target exe missing before clean, continuing"',
    ') else (',
    '  call :log "target exe exists before clean"',
    ')',
    'if not exist "%TARGET_APP_ASAR%" (',
    '  call :log "target app.asar missing before clean, continuing"',
    ') else (',
    '  call :log "target app.asar exists before clean"',
    ')',
    'for %%D in (C D E F G H I J K L M N O P Q R S T U V W X Y Z) do (',
    '  if /i "%INSTALL_DIR%" == "%%D:\\" (',
    '    call :log "install dir is a drive root, aborting"',
    '    exit /b 13',
    '  )',
    ')',
    'set "CLEAN_RETRY_COUNT=0"',
    ':clean_retry',
    'set /a CLEAN_RETRY_COUNT+=1',
    'call :log "clean start (attempt %CLEAN_RETRY_COUNT%)"',
    'call :log "clean start"',
    'call :log "cleaning install directory"',
    'for /f "delims=" %%I in (\'dir /a /b "%INSTALL_DIR%" 2^>nul\') do (',
    '  if exist "%INSTALL_DIR%\\%%I\\" (',
    '    call :log "clean delete attempt [dir] %%I"',
    '    rmdir /s /q "%INSTALL_DIR%\\%%I" >> "%LOG_PATH%" 2>&1',
    '    set "DELETE_ERRORLEVEL=!ERRORLEVEL!"',
    '    if exist "%INSTALL_DIR%\\%%I\\" (',
    '      call :log "clean delete failed [dir] %%I errorlevel=!DELETE_ERRORLEVEL!"',
    '      call :log "clean directory remains after delete: %INSTALL_DIR%\\%%I"',
    '    ) else (',
    '      call :log "clean delete succeeded [dir] %%I errorlevel=!DELETE_ERRORLEVEL!"',
    '    )',
    '  ) else (',
    '    call :log "clean delete attempt [file] %%I"',
    '    del /f /q "%INSTALL_DIR%\\%%I" >> "%LOG_PATH%" 2>&1',
    '    set "DELETE_ERRORLEVEL=!ERRORLEVEL!"',
    '    if exist "%INSTALL_DIR%\\%%I" (',
    '      call :log "clean delete failed [file] %%I errorlevel=!DELETE_ERRORLEVEL!"',
    '      call :log "clean file remains after delete: %INSTALL_DIR%\\%%I"',
    '    ) else (',
    '      call :log "clean delete succeeded [file] %%I errorlevel=!DELETE_ERRORLEVEL!"',
    '    )',
    '  )',
    ')',
    'call :log "clean finished"',
    'if exist "%TARGET_EXE%" (',
    '  call :log "target exe exists after clean = true"',
    ') else (',
    '  call :log "target exe exists after clean = false"',
    ')',
    'if exist "%INSTALL_DIR%\\resources\\" (',
    '  call :log "target resources dir exists after clean = true"',
    ') else (',
    '  call :log "target resources dir exists after clean = false"',
    ')',
    'if exist "%TARGET_APP_ASAR%" (',
    '  call :log "target app.asar exists after clean = true"',
    ') else (',
    '  call :log "target app.asar exists after clean = false"',
    ')',
    'call :inspect_install_dir_state',
    'if "!INSTALL_DIR_ITEM_COUNT!"=="0" (',
    '  call :log "install directory empty check result = empty path=%INSTALL_DIR%"',
    ') else (',
    '  call :log "install directory empty check result = not-empty count=!INSTALL_DIR_ITEM_COUNT! path=%INSTALL_DIR%"',
    '  call :log "install directory still has entries after clean attempt %CLEAN_RETRY_COUNT%"',
    '  if "!INSTALL_DIR_ENUM_LOGGED_COUNT!"=="0" call :log "remaining entry enumeration found 0 items"',
    '  if %CLEAN_RETRY_COUNT% LSS 3 (',
    '    call :log "clean retry wait start"',
    '    timeout /t 1 /nobreak >nul',
    '    call :log "clean retry wait finished"',
    '    goto clean_retry',
    '  )',
    '  call :log "clean failed after retries"',
    '  exit /b 17',
    ')',
    'call :log "robocopy start"',
    'call :log "copying extracted files into install directory"',
    'robocopy "%SOURCE_DIR%" "%INSTALL_DIR%" /E /COPY:DAT /DCOPY:DAT /R:2 /W:1 /NFL /NDL /NJH /NJS >> "%LOG_PATH%" 2>&1',
    'set "ROBOCOPY_EXIT=%ERRORLEVEL%"',
    'call :log "robocopy finished with exit code %ROBOCOPY_EXIT%"',
    'if %ROBOCOPY_EXIT% GEQ 8 (',
    '  call :log "robocopy failed with exit code %ROBOCOPY_EXIT%"',
    '  exit /b %ROBOCOPY_EXIT%',
    ')',
    'if not exist "%TARGET_EXE%" (',
    '  call :log "target exe missing after copy"',
    '  exit /b 11',
    ')',
    'call :log "target exe exists after copy"',
    'if not exist "%TARGET_APP_ASAR%" (',
    '  call :log "target app.asar missing after copy"',
    '  exit /b 18',
    ')',
    'call :log "target app.asar exists after copy"',
    'if not exist "%TARGET_EXE%" (',
    '  call :log "target exe missing before restart, aborting"',
    '  exit /b 15',
    ')',
    'call :log "target exe exists before restart"',
    'if not exist "%TARGET_APP_ASAR%" (',
    '  call :log "target app.asar missing before restart, aborting"',
    '  exit /b 19',
    ')',
    'call :log "target app.asar exists before restart"',
    'call :log "launching new exe"',
    'start "" "%TARGET_EXE%"',
    'call :log "restart command issued"',
    'call :log "restart command returned"',
    'start "" cmd /c ping 127.0.0.1 -n 3 >nul ^& del /f /q "%~f0" >nul 2^>^&1',
    'exit /b 0',
    ':inspect_install_dir_state',
    'set "INSTALL_DIR_ITEM_COUNT=0"',
    'set "INSTALL_DIR_ENUM_LOGGED_COUNT=0"',
    "powershell -NoProfile -Command \"$installDir = $env:INSTALL_DIR; $items = @(Get-ChildItem -LiteralPath $installDir -Force -ErrorAction SilentlyContinue); Write-Output ('COUNT|' + $items.Count); foreach ($item in $items) { $kind = if ($item.PSIsContainer) { 'dir' } else { 'file' }; $relative = [System.IO.Path]::GetRelativePath($installDir, $item.FullName); Write-Output ('ENTRY|' + $kind + '|' + $relative) }\" > \"%ENUM_OUTPUT%\" 2>&1",
    'for /f "usebackq delims=" %%I in ("%ENUM_OUTPUT%") do (',
    '  set "ENUM_LINE=%%I"',
    '  if "!ENUM_LINE:~0,6!"=="COUNT|" set "INSTALL_DIR_ITEM_COUNT=!ENUM_LINE:~6!"',
    '  if "!ENUM_LINE:~0,6!"=="ENTRY|" (',
    '    for /f "tokens=1,2,3 delims=|" %%A in ("!ENUM_LINE!") do (',
    '      set /a INSTALL_DIR_ENUM_LOGGED_COUNT+=1',
    '      call :log "remaining entry [%%B] %%C"',
    '    )',
    '  )',
    ')',
    'goto :eof',
    ':check_pid_running',
    'set "TASKLIST_PID="',
    'for /f "usebackq tokens=2 delims=," %%A in (`tasklist /FI "PID eq %APP_PID%" /FO CSV /NH 2^>nul`) do set "TASKLIST_PID=%%~A"',
    'if defined TASKLIST_PID (',
    '  call :log "tasklist matched pid !TASKLIST_PID!"',
    ') else (',
    '  call :log "tasklist matched no pid"',
    ')',
    'if "!TASKLIST_PID!"=="%APP_PID%" exit /b 0',
    'exit /b 1',
    ':log',
    '>> "%LOG_PATH%" echo [%DATE% %TIME%] %~1',
    'goto :eof',
    ''
  ].join('\r\n')

  await fs.promises.writeFile(scriptPath, script, 'utf-8')

  return {
    scriptPath,
    logPath
  }
}
